title: "TREC 2024: Million LLMs"
email: e.kanoulas@uva.nl
description: >- # this means to ignore newlines until "baseurl:"
  Defining "Search" in a world where the front-facing entity
  for every organization is a Conversational AI.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://trec-mllm.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme

